- id: check-header-footer
  name: Check Headers & Footers
  description: Check the header and footer of files.
  entry: check-header-footer
  language: python
  types: [text]
  stages: [commit, push, manual]
- id: arabic-presentation-form
  name: Arabic Presentation Form Normalizer
  description: Replaces Arabic Presentation for and other contextual forms to default.
  entry: arabic-presentation-form
  language: python
  types: [text]
  stages: [commit, push, manual]
